#!/bin/bash

STATUS=$1
DESC=$2
URL=$3

data="{\"state\":\"$STATUS\","
if [ ! -z "$URL" ]
then
    data="$data\"target_url\":\"$URL\","
fi
data="$data\"description\":\"$DESC\",\"context\":\"surge.sh/staging\"}"

curl -u $GITHUB_AUTH_USER:$GITHUB_PR_TOKEN --data "$data" "https://api.github.com/repos/$GITHUB_USER/$GITHUB_REPO/statuses/$TRAVIS_PULL_REQUEST_SHA" > /dev/null
